/*
 * Copyright (C) 2018 Joaquin Martinez <juacom04@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.improvisados.jmastermind.gui.panels;

import com.improvisados.jmastermind.gui.Theme;
import com.improvisados.jmastermind.gui.components.MultiLineToolTip;
import com.improvisados.jmastermind.gui.controllers.ThemeController;
import com.improvisados.jmastermind.logic.Guess;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JToolTip;
import javax.swing.border.LineBorder;

public class PGuess extends javax.swing.JPanel
{

    /**
     * Creates new form PGuess
     */
    public PGuess(Guess g,Color[] symbols)
    {
        initComponents();
        final Theme theme = ThemeController.getInstance().getCurrentTheme();

        int spacing = Theme.SPACING;
        int size = Theme.TOKEN_SIZE;
        int resultSize=size/2;

        int[] guess = g.getGuess();
        JLabel lGuess;
        JLabel lResult;
        int x;
        int blackLeft = g.getBlacks();
        int whiteLeft = g.getWhites();
        setBackground(theme.getBackgroundColor());
        


        for (int i = 0; i < guess.length; i++)
        {
            lGuess = new JLabel();
            lGuess.setBounds((size +spacing) * i ,0,size,size);
            lGuess.setIcon(theme.getToken());
            lGuess.setOpaque(true);
            //TODO: set the rigth background color 
            lGuess.setBackground(symbols[guess[i]]);
            add(lGuess);

            lResult = new JLabel(""+i){
                @Override
                public JToolTip createToolTip()
                {
                    JToolTip old=super.createToolTip();
                    
                    MultiLineToolTip tool=new MultiLineToolTip();
                    tool.setTipText(old.getTipText());
                    tool.setToolTipText(old.getToolTipText());
                    tool.setComponent(this);                    
                    tool.setBackground(theme.getBackgroundColor());
                    tool.setForeground(theme.getForegroundColor());
                    tool.setBorder(new LineBorder(theme.getDefaultTokenColor()));
                    return tool;
                }                
            };
                        

            lResult.setSize(resultSize, resultSize);

            x =(size+spacing)*guess.length+((size/4)*i)-((size/4)*(i%2));
            


            lResult.setLocation(x, (i % 2) *resultSize);
            lResult.setOpaque(true);
            lResult.setIcon(theme.getResult());

            if (blackLeft > 0)
            {
                lResult.setBackground(Color.BLACK);
                blackLeft--;
            }
            else if (whiteLeft > 0)
            {
                lResult.setBackground(Color.WHITE);
                whiteLeft--;
            }
            else
            {
                lResult.setBackground(theme.getDefaultTokenColor());
            }

            lResult.setToolTipText(g.getBlacks()+" Rigth Colors in the rigth place"+System.getProperty("line.separator")+g.getWhites()+" Rigth Color in the wrong place");

            add(lResult);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
